/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AcademicHome: typeof import('./src/components/academic/academicHome.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppSnackbar: typeof import('./src/components/snackBar/AppSnackbar.vue')['default']
    ConfirmationDialog: typeof import('./src/components/students/ConfirmationDialog.vue')['default']
    DashboardActivityCard: typeof import('./src/components/cards/DashboardActivityCard.vue')['default']
    DashboardCard: typeof import('./src/components/cards/DashboardCard.vue')['default']
    DashboardChartCard: typeof import('./src/components/cards/DashboardChartCard.vue')['default']
    FormField: typeof import('./src/components/forms/FormField.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudentDataTable: typeof import('./src/components/students/StudentDataTable.vue')['default']
  }
}
